### PR TITLE
Fix plural of "they" to "he"

### LINKED ISSUE #154: Plural of "they" is "he". Bug it becomes "she".
The plural of "they" is "he". It is becoming "she". This was an embarrassing when my community pointed out this mistake with feedback like "are you giving us all love?". Please fix to respect giving "he".

"She" should be for "country" "boats" or other inanimate objects. This is hard to detect but "they" is always used humans, so respect giving "he" is accurate.

### PR DESCRIPTION
**Pull request by Noitidart**
Fixes #154

### CODE REVIEW

**Comment by wopian** [comment]
`They` should return `they` as `they` is now a widely accepted gender-neutral pronoun (or a personal preference to be referred to as).

Returning he (or she as it appears to be doing right now) is destructive behaviour as passing in:

- "he" to be pluralised will return "they", but be singularised to "she" (in existing code);
- "she" to be pluralised will return "they", but be singularised to "he" (in this PR);
- "they" to be pluralised will return "they" but be singularised to "she" (in existing code), we don't know if they were female, it could be pluralising the pronoun of someone who wants to be referred to as `they`;
- "they" to be pluralised will return "they" but be singularised to "he" (in this PR), same reason as above.

https://dictionary.cambridge.org/dictionary/english/they

**Comment by Noitidart** [comment]
Hi @wopian please see chat in #154 - it being widely accepted is a bold statement which I don't think is true.

**Comment by wopian** [comment]
> It is also not about personal preference but generic respect.

Those are not mutually exclusive. If a user selects "they" in your program settings and you have the following string:

`{ pronoun } liked your post` where `pronoun` is `toSingular(settings.pronoun)`, it should be:
- `He liked your post` for `he`
- `She liked your post` for `she`
- `They liked your post` for `they`

Turning `They liked your post` to `He/She liked your post` is not respectful. I'd also argue it's not generic as it modifies the gendered (pro)nouns returned in the response (she -> they -> he)

**Comment by Noitidart** [comment]
I respectfully ask you to please refer to chat in #154 - This is not personal preference in settings. This is general which is "he" to convey respect, "he liked your post". "she" is used for love as in country. Respect is opted for over love. Love is intimate, and not given to everyone "generic". Every language follow this pattern.

**Comment by Noitidart** [comment]
Dang this bug still lives. Isn't they to he preferred over they to she? Or do you prefer the "she"?

**Pull request closed without merging**
