### PR TITLE
Add possessive pronouns

### PR DESCRIPTION
**Pull request by thomasrockhu**
Absolutely love this library and ran into a possessive pronoun use case.

### CODE REVIEW

**Comment by thomasrockhu** [comment]
Bump, would love to get this merged in if it looks ok

**Comment by thomasrockhu** [comment]
Casual bump on this

**Comment by thomasrockhu** [comment]
@blakeembrey is this repository dead? I'd be happy to help if the issue is time

**Comment by blakeembrey** [comment]
Not exactly dead, but not actively worked on. Sorry. Happy to merge this.

**Comment by thomasrockhu** [comment]
@blakeembrey no worries, I totally get it! Offer stands if you need some help maintaining.

**Pull request merged**
